export const meta = {
  id: "awsom",
  name: "Alice Walton School of Medicine",
  subtitle: "Bentonville",
  client: "AWSOM",
  source: "TAB Final Report 23 05 93",
  generated: "12/23/2025",
  label: "AWSOM · Alice Walton School of Medicine — Bentonville",
  phase: "Commissioning",
  categories: ["All", "Programming", "VFD / Setpoint", "Setpoint Verify", "Setpoint Update", "Airflow Review", "Sensor Verify", "FYI / Verify", "FYI / Document"],
};

export const items = [
  {
    id: 1,
    priority: "HIGH",
    unit: "RF-02",
    category: "Programming",
    issue: "Fan designed to modulate on building pressure but ran at 100% during TAB. Modulation sequence not yet commissioned.",
    action: "Complete BAS modulation setup for RF-02. Once active, cap Max VFD speed at 70% per TAB directive.",
    source: "TAB Notes — RF-02",
    status: "OPEN",
  },
  {
    id: 2,
    priority: "HIGH",
    unit: "EF-01",
    category: "VFD / Setpoint",
    issue: "Fan rated to operate at 67 Hz. TAB found VFD running at 53 Hz — delivering 22,185 CFM vs. 22,500 CFM design.",
    action: "Verify BAS VFD frequency cap for EF-01. Raise upper limit to 67 Hz if BAS is restricting output.",
    source: "TAB Notes — EF-01",
    status: "OPEN",
  },
  {
    id: 3,
    priority: "HIGH",
    unit: "EF-02",
    category: "VFD / Setpoint",
    issue: "Fan rated to operate at 67 Hz. TAB found VFD running at 53 Hz — delivering 22,220 CFM vs. 22,500 CFM design.",
    action: "Verify BAS VFD frequency cap for EF-02. Raise upper limit to 67 Hz if BAS is restricting output.",
    source: "TAB Notes — EF-02",
    status: "OPEN",
  },
  {
    id: 4,
    priority: "HIGH",
    unit: "EF-04",
    category: "Airflow Review",
    issue: "Fan at 100% but cannot achieve design airflow to duct trunk serving grilles 26–31. Likely mechanical obstruction.",
    action: "Flag in BAS asset notes. If airflow tracking/alarms exist on EF-04, expect shortfall on that trunk until mechanical issue is resolved.",
    source: "TAB Notes — EF-04",
    status: "OPEN",
  },
  {
    id: 5,
    priority: "MEDIUM",
    unit: "AHU-02 / Return Fan",
    category: "Setpoint Verify",
    issue: "Return fan set to maintain 0.75\" suction pressure. Design TSP 1.7\", ESP 1.2\".",
    action: "Confirm 0.75\" suction pressure setpoint is active and correct in BAS return fan control loop.",
    source: "TAB Notes — AHU-02",
    status: "OPEN",
  },
  {
    id: 6,
    priority: "MEDIUM",
    unit: "AHU-01-S",
    category: "Setpoint Verify",
    issue: "TAB documented SP reset range: 1.0–1.5\".",
    action: "Confirm BAS static pressure reset setpoint range matches 1.0–1.5\" for AHU-01-S.",
    source: "TAB Notes — AHU-01-S/SPP-01",
    status: "OPEN",
  },
  {
    id: 7,
    priority: "MEDIUM",
    unit: "AHU-02",
    category: "Setpoint Verify",
    issue: "TAB documented SP reset range: 1.0–1.5\".",
    action: "Confirm BAS static pressure reset setpoint range matches 1.0–1.5\" for AHU-02.",
    source: "TAB Notes — AHU-02/SPP-01",
    status: "OPEN",
  },
  {
    id: 8,
    priority: "MEDIUM",
    unit: "AHU-03",
    category: "Setpoint Verify",
    issue: "TAB documented SP reset range: 1.0–2.0\" (wider than other AHUs).",
    action: "Confirm BAS static pressure reset setpoint range matches 1.0–2.0\" for AHU-03.",
    source: "TAB Notes — AHU-03/SPP-01",
    status: "OPEN",
  },
  {
    id: 9,
    priority: "MEDIUM",
    unit: "AHU-05",
    category: "Setpoint Verify",
    issue: "TAB documented SP reset range: 1.0–1.5\". Min OSA: 10,350 CFM.",
    action: "Confirm BAS SP reset range matches 1.0–1.5\" and minimum OSA setpoint is 10,350 CFM for AHU-05.",
    source: "TAB Notes — AHU-05/SPP-01",
    status: "OPEN",
  },
  {
    id: 10,
    priority: "MEDIUM",
    unit: "AHU-01-WA",
    category: "Setpoint Verify",
    issue: "ERU exhaust fan set to maintain 0.60\" duct static. Exhaust fan rated 25,000 CFM; heat wheel exhaust 11,250 CFM / OSA 11,250 CFM.",
    action: "Verify 0.60\" exhaust duct static setpoint is programmed in BAS for AHU-01-WA exhaust fan.",
    source: "TAB Notes — AHU-01-WA",
    status: "OPEN",
  },
  {
    id: 11,
    priority: "MEDIUM",
    unit: "AHU-04-WA",
    category: "Setpoint Verify",
    issue: "ERU exhaust fan set to maintain 0.60\" duct static. Exhaust fan rated 18,000 CFM; heat wheel exhaust 8,100 CFM / OSA 8,900 CFM.",
    action: "Verify 0.60\" exhaust duct static setpoint is programmed in BAS for AHU-04-WA exhaust fan.",
    source: "TAB Notes — AHU-04-WA",
    status: "OPEN",
  },
  {
    id: 12,
    priority: "MEDIUM",
    unit: "PCHWP-01",
    category: "Sensor Verify",
    issue: "TAB recorded CHW DP sensor readings at multiple staging conditions: 8 PSI (2 pumps/CH-1 only), 22 PSI (4 pumps/both chillers), 9 PSI (4 pumps/CH-1 only).",
    action: "Verify BAS CHW DP control setpoints and pump staging logic align with these observed operating bands.",
    source: "TAB Notes — PCHWP-01",
    status: "OPEN",
  },
  {
    id: 13,
    priority: "MEDIUM",
    unit: "CH-01",
    category: "Setpoint Verify",
    issue: "BAS controlling heat recovery side to 6 PSI chiller DP per manufacturer recommendation.",
    action: "Verify 6 PSI chiller DP setpoint is active and correctly programmed for CH-01 heat recovery side.",
    source: "TAB Notes — CH-01",
    status: "OPEN",
  },
  {
    id: 14,
    priority: "MEDIUM",
    unit: "CH-01 / CH-02",
    category: "Setpoint Verify",
    issue: "BAS controlling CHW pumps via system DP and bypass valve to maintain 3 PSI minimum chiller DP for flow protection.",
    action: "Verify CHW bypass control logic is functioning. Confirm 3 PSI minimum DP setpoint is correct for both chillers.",
    source: "TAB Notes — CH-01 / CH-02",
    status: "OPEN",
  },
  {
    id: 15,
    priority: "MEDIUM",
    unit: "VAV-2-24 (AHU-02)",
    category: "Setpoint Update",
    issue: "Plans showed 11 grilles but only 9 installed. TAB reduced design max airflow from 2,080 → 1,700 CFM.",
    action: "Update VAV-2-24 max cooling CFM setpoint in BAS from 2,080 to 1,700 CFM.",
    source: "TAB Notes — AHU-02/VAV-2-24",
    status: "OPEN",
  },
  {
    id: 16,
    priority: "MEDIUM",
    unit: "VAV-2-17 (AHU-02)",
    category: "Setpoint Update",
    issue: "Installed grilles only total 340 CFM vs. VAV box design of 380 CFM. TAB set box to 340 CFM actual.",
    action: "Confirm BAS max cooling setpoint for VAV-2-17 is set to 340 CFM, not 380 CFM.",
    source: "TAB Notes — AHU-02/VAV-2-17",
    status: "OPEN",
  },
  {
    id: 17,
    priority: "LOW",
    unit: "FCU-12",
    category: "FYI / Verify",
    issue: "Controls contractor confirmed cooling only — no heating capability. HW coil/valve present but heating disabled per controls.",
    action: "Confirm BAS is not attempting to enable heating on FCU-12 and not generating heating failure alarms.",
    source: "TAB Notes — FCU-12",
    status: "OPEN",
  },
  {
    id: 18,
    priority: "LOW",
    unit: "All VAV Terminal Boxes",
    category: "FYI / Document",
    issue: "BAS LAT limit confirmed at 85°F for all VAV heating by TAB.",
    action: "No change needed. Document as TAB-confirmed. Verify BAS limit is 85°F if audited.",
    source: "Report Summary — Terminal Boxes",
    status: "NOTED",
  },
  {
    id: 19,
    priority: "LOW",
    unit: "EF-03",
    category: "FYI / Document",
    issue: "Fan inaccessible at installed location. Motor RPM and full data could not be verified by TAB.",
    action: "Note in BAS asset records. Monitor for runtime faults. Flag for physical access resolution.",
    source: "TAB Notes — EF-03",
    status: "NOTED",
  },
];
