export const meta = {
  id: "cbmaa-retro",
  name: "CBMAA Retro",
  subtitle: "Retrocommissioning",
  client: "ES2",
  type: "checklist",
  phase: "Retro",
  label: "ES2 · CBMAA Retrocommissioning",
  generated: "6/5/2026",
};

export const items = [
  { id: 1,  text: "AHU-1/2 install",                                                                         done: true  },
  { id: 2,  text: "VAV 1-5 install",                                                                          done: true  },
  { id: 3,  text: "FCU install",                                                                               done: true  },
  { id: 4,  text: "Commission devices",                                                                        done: true  },
  { id: 5,  text: "Stickers on 4 squares",                                                                     done: true  },
  { id: 6,  text: "Email about CAT GEN modbus integration",                                                    done: true  },
  { id: 7,  text: "AHU-2 MAT",                                                                                 done: false },
  { id: 8,  text: "Email about phase 2 and FLW / bathroom IP",                                                done: true  },
  { id: 9,  text: "Trail bathroom recontrol",                                                                  done: true  },
  { id: 10, text: "FLW House recontrol",                                                                       done: true  },
  { id: 11, text: "FLW House IP test",                                                                         done: true  },
  { id: 12, text: "FLW Program and Graphics",                                                                  done: true  },
  { id: 13, text: "Review Phase 2 proof",                                                                      done: true  },
  { id: 14, text: "CRAC unit lead lag logic",                                                                  done: false },
  { id: 15, text: "Repair FCU E2",                                                                             done: true  },
  { id: 16, text: "2 CHW plant controllers exist (PXCM16 and PNL23) — find out how these differ. Affects phase 4 and 9, mend as needed.", done: false },
  { id: 17, text: "Locate AHU-4 TSTATs in the vault",                                                        done: false },
  { id: 18, text: "Relabel AHU-3/4 panel (all wires)",                                                       done: false },
  { id: 19, text: "Configure AHU-7, AHU-8 flow meters",                                                      done: false },
  { id: 20, text: "Ping engineering for graphics",                                                            done: false },
  { id: 21, text: "Organize a plan of action for office VAV recontrol",                                       done: false },
];
