export const meta = {
  id: "cbmaa-retro",
  name: "CBMAA Retro",
  subtitle: "Retrocommissioning",
  client: "ES2",
  phase: "Retro",
  label: "ES2 · CBMAA Retrocommissioning",
  source: "Field Task Log",
  generated: "6/5/2026",
  categories: ["All", "Install", "Commissioning", "Programming", "Field Work", "Coordination", "Investigation", "Planning"],
};

export const items = [
  {
    id: 1,
    priority: "HIGH",
    unit: "AHU-1/2",
    category: "Install",
    issue: "AHU-1/2 installation pending.",
    action: "Complete AHU-1/2 installation.",
    source: "Field Task Log",
    status: "RESOLVED",
  },
  {
    id: 2,
    priority: "HIGH",
    unit: "VAV-1 thru 5",
    category: "Install",
    issue: "VAV 1–5 installation pending.",
    action: "Complete VAV 1–5 installation.",
    source: "Field Task Log",
    status: "RESOLVED",
  },
  {
    id: 3,
    priority: "HIGH",
    unit: "FCU",
    category: "Install",
    issue: "FCU installation pending.",
    action: "Complete FCU installation.",
    source: "Field Task Log",
    status: "RESOLVED",
  },
  {
    id: 4,
    priority: "HIGH",
    unit: "All Devices",
    category: "Commissioning",
    issue: "Devices installed but not yet commissioned.",
    action: "Commission all installed devices. Verify BAS points and operation.",
    source: "Field Task Log",
    status: "RESOLVED",
  },
  {
    id: 5,
    priority: "LOW",
    unit: "Controls Panels",
    category: "Field Work",
    issue: "4 control panel squares missing identification stickers.",
    action: "Apply stickers to all 4 squares.",
    source: "Field Task Log",
    status: "RESOLVED",
  },
  {
    id: 6,
    priority: "MEDIUM",
    unit: "CAT GEN",
    category: "Coordination",
    issue: "Modbus integration requirements for CAT generator not confirmed.",
    action: "Email stakeholders regarding CAT GEN Modbus integration scope and requirements.",
    source: "Field Task Log",
    status: "RESOLVED",
  },
  {
    id: 7,
    priority: "HIGH",
    unit: "AHU-2",
    category: "Programming",
    issue: "Mixed air temperature (MAT) sensor or sequence not yet verified in BAS.",
    action: "Verify AHU-2 MAT sensor reading and confirm correct use in economizer/mixing logic.",
    source: "Field Task Log",
    status: "OPEN",
  },
  {
    id: 8,
    priority: "MEDIUM",
    unit: "Phase 2 / FLW",
    category: "Coordination",
    issue: "Phase 2 scope and FLW/bathroom IP addressing not confirmed with team.",
    action: "Email team regarding Phase 2 plan and FLW/bathroom IP address coordination.",
    source: "Field Task Log",
    status: "RESOLVED",
  },
  {
    id: 9,
    priority: "MEDIUM",
    unit: "Trail Bathroom",
    category: "Field Work",
    issue: "Trail bathroom controls due for recontrol.",
    action: "Complete trail bathroom recontrol. Verify BAS points after.",
    source: "Field Task Log",
    status: "RESOLVED",
  },
  {
    id: 10,
    priority: "MEDIUM",
    unit: "FLW House",
    category: "Field Work",
    issue: "FLW House controls due for recontrol.",
    action: "Complete FLW House recontrol.",
    source: "Field Task Log",
    status: "RESOLVED",
  },
  {
    id: 11,
    priority: "MEDIUM",
    unit: "FLW House",
    category: "Field Work",
    issue: "FLW House IP connectivity not yet tested post-recontrol.",
    action: "Run IP test on FLW House after recontrol. Confirm BAS communication.",
    source: "Field Task Log",
    status: "RESOLVED",
  },
  {
    id: 12,
    priority: "MEDIUM",
    unit: "FLW House",
    category: "Programming",
    issue: "FLW House programming and graphics not yet complete.",
    action: "Complete BAS programming and graphics for FLW House.",
    source: "Field Task Log",
    status: "RESOLVED",
  },
  {
    id: 13,
    priority: "MEDIUM",
    unit: "Phase 2",
    category: "Coordination",
    issue: "Phase 2 proof documents need review.",
    action: "Review Phase 2 proof. Flag any discrepancies or required changes.",
    source: "Field Task Log",
    status: "RESOLVED",
  },
  {
    id: 14,
    priority: "HIGH",
    unit: "CRAC",
    category: "Programming",
    issue: "CRAC unit lead/lag logic not yet programmed.",
    action: "Program and test lead/lag staging logic for CRAC units in BAS.",
    source: "Field Task Log",
    status: "OPEN",
  },
  {
    id: 15,
    priority: "MEDIUM",
    unit: "FCU-E2",
    category: "Field Work",
    issue: "FCU-E2 reported faulty — needs repair.",
    action: "Repair FCU-E2. Verify normal operation and BAS point restoration after.",
    source: "Field Task Log",
    status: "RESOLVED",
  },
  {
    id: 16,
    priority: "HIGH",
    unit: "PXCM16 / PNL23",
    category: "Investigation",
    issue: "Two CHW plant controllers exist (PXCM16 and PNL23). Functional differences unknown. Affects Phase 4 and 9 scope.",
    action: "Investigate how PXCM16 and PNL23 differ. Document findings and mend Phase 4/9 plans as needed.",
    source: "Field Task Log",
    status: "OPEN",
  },
  {
    id: 17,
    priority: "MEDIUM",
    unit: "AHU-4",
    category: "Field Work",
    issue: "AHU-4 thermostats believed to be located in the vault — not yet confirmed.",
    action: "Locate AHU-4 TSTATs in the vault. Document location for future access.",
    source: "Field Task Log",
    status: "OPEN",
  },
  {
    id: 18,
    priority: "MEDIUM",
    unit: "AHU-3/4 Panel",
    category: "Field Work",
    issue: "AHU-3/4 control panel wiring labels are incorrect or missing.",
    action: "Relabel all wires in AHU-3/4 panel to match as-built documentation.",
    source: "Field Task Log",
    status: "OPEN",
  },
  {
    id: 19,
    priority: "HIGH",
    unit: "AHU-7 / AHU-8",
    category: "Programming",
    issue: "Flow meters on AHU-7 and AHU-8 not yet configured in BAS.",
    action: "Configure AHU-7 and AHU-8 flow meters in BAS. Verify readings against design.",
    source: "Field Task Log",
    status: "OPEN",
  },
  {
    id: 20,
    priority: "MEDIUM",
    unit: "Graphics",
    category: "Coordination",
    issue: "Engineering graphics not yet received.",
    action: "Ping engineering team for graphics deliverables. Set follow-up deadline.",
    source: "Field Task Log",
    status: "OPEN",
  },
  {
    id: 21,
    priority: "HIGH",
    unit: "Office VAVs",
    category: "Planning",
    issue: "Office VAV recontrol scope has no organized plan of action.",
    action: "Develop and document a plan of action for office VAV recontrol sequence.",
    source: "Field Task Log",
    status: "OPEN",
  },
];
