export const meta = {
  id: "crystal-bridges",
  name: "Crystal Bridges Museum",
  subtitle: "BAS Retrofit",
  client: "ES2",
  source: "TAB Report Book 6-5-26",
  generated: "6/5/2026",
  label: "ES2 · Crystal Bridges Museum BAS Retrofit",
  phase: "Commissioning",
  categories: ["All", "Programming", "Sensor Cal", "EBTRON Verify", "Airflow Review", "Setpoint Update", "FYI / No Action"],
};

export const items = [
  {
    id: 1,
    priority: "HIGH",
    unit: "CDWP-A7-01/02/03",
    category: "Programming",
    issue: "Fixed DP setpoint (6 PSI) causes over/under-flow depending on number of active CT cells.",
    action: "Update BAS program with 3 separate DP setpoints tied to number of active cooling tower cells.",
    source: "TAB Notes — Pump Section",
    status: "OPEN",
  },
  {
    id: 2,
    priority: "HIGH",
    unit: "CHWP-A7-01",
    category: "Programming",
    issue: "Fixed DP setpoint (8 PSI) causes over/under-flow with chiller/cell staging.",
    action: "Update BAS program with staged DP setpoints based on active chiller/CT cell count.",
    source: "TAB Notes — Pump Section",
    status: "OPEN",
  },
  {
    id: 3,
    priority: "MEDIUM",
    unit: "CDWP-A7-02",
    category: "Sensor Cal",
    issue: "Condenser water supply flow meter reads ~200 GPM low vs. accurate return meter.",
    action: "Calibrate supply-side flow meter. Verify BAS staging/efficiency logic uses corrected value.",
    source: "TAB Notes — CDWP-A7-02",
    status: "OPEN",
  },
  {
    id: 4,
    priority: "MEDIUM",
    unit: "CDWP-A7-03",
    category: "Sensor Cal",
    issue: "Condenser water supply flow meter reads ~200 GPM low vs. accurate return meter.",
    action: "Calibrate supply-side flow meter. Verify BAS staging/efficiency logic uses corrected value.",
    source: "TAB Notes — CDWP-A7-03",
    status: "OPEN",
  },
  {
    id: 5,
    priority: "MEDIUM",
    unit: "CHWP-A7-01",
    category: "Sensor Cal",
    issue: "CHW supply meter ~400 GPM low; return meter ~500 GPM low. Both inaccurate.",
    action: "Calibrate both CHW flow meters. Audit any BAS logic dependent on these readings.",
    source: "TAB Notes — CHWP-A7-01",
    status: "OPEN",
  },
  {
    id: 6,
    priority: "MEDIUM",
    unit: "ERU-A7-01",
    category: "EBTRON Verify",
    issue: "EBTRON gains applied: Return 0.54 / OSA 0.93 / Exhaust 1.20",
    action: "Confirm BAS is receiving accurate post-calibration readings. Validate airflow alarms/setpoints.",
    source: "TAB Notes — ERU-A7-01",
    status: "OPEN",
  },
  {
    id: 7,
    priority: "MEDIUM",
    unit: "ERU-A7-02",
    category: "EBTRON Verify",
    issue: "EBTRON gains applied: Return 1.06 / OSA 1.25 / Exhaust 0.86",
    action: "Confirm BAS readings post-calibration. Validate airflow alarms/setpoints.",
    source: "TAB Notes — ERU-A7-02",
    status: "OPEN",
  },
  {
    id: 8,
    priority: "MEDIUM",
    unit: "ERU-A7-03",
    category: "EBTRON Verify",
    issue: "EBTRON gains applied: Return 1.35 / OSA 1.14 / Exhaust 1.16. Supply grilles only total 1,475 of 2,600 CFM design.",
    action: "Confirm BAS readings post-calibration. Review ERU supply airflow setpoint — installed condition differs from design.",
    source: "TAB Notes — ERU-A7-03",
    status: "OPEN",
  },
  {
    id: 9,
    priority: "MEDIUM",
    unit: "ERU-A8-01",
    category: "EBTRON Verify",
    issue: "EBTRON gains applied: Return 0.91 / OSA 0.89 / Exhaust 0.85",
    action: "Confirm BAS readings post-calibration. Validate airflow alarms/setpoints.",
    source: "TAB Notes — ERU-A8-01",
    status: "OPEN",
  },
  {
    id: 10,
    priority: "MEDIUM",
    unit: "ERU-A9-01",
    category: "EBTRON Verify",
    issue: "EBTRON gains applied: Return 0.93 / OSA 1.90 / Exhaust 1.00. OSA gain is notably high.",
    action: "Spot-check OSA reading in WebCTRL — 1.90 gain is significant. Validate post-cal airflow values.",
    source: "TAB Notes — ERU-A9-01",
    status: "OPEN",
  },
  {
    id: 11,
    priority: "MEDIUM",
    unit: "ERU-A9-02",
    category: "EBTRON Verify",
    issue: "EBTRON gains applied: Return 0.91 / OSA 1.23 / Exhaust 1.03",
    action: "Confirm BAS readings post-calibration. Validate airflow alarms/setpoints.",
    source: "TAB Notes — ERU-A9-02",
    status: "OPEN",
  },
  {
    id: 12,
    priority: "MEDIUM",
    unit: "ERU-A9-03",
    category: "EBTRON Verify",
    issue: "EBTRON gains applied: Return 0.98 / OSA 1.54 / Exhaust 1.35. OSA gain elevated.",
    action: "Spot-check OSA reading in WebCTRL. Validate post-cal airflow values.",
    source: "TAB Notes — ERU-A9-03",
    status: "OPEN",
  },
  {
    id: 13,
    priority: "MEDIUM",
    unit: "FCU-A9-01",
    category: "Airflow Review",
    issue: "Unit short of design CFM at high speed (741 vel grid / 815 pitot). Both below design.",
    action: "Check BAS for min airflow alarms on this unit. Coordinate with mechanical on root cause.",
    source: "TAB Notes — FCU-A9-01",
    status: "OPEN",
  },
  {
    id: 14,
    priority: "MEDIUM",
    unit: "ERU-A7-03",
    category: "Airflow Review",
    issue: "Supply grilles total 1,475 CFM vs. 2,600 CFM design. TAB set return/exhaust to match offset.",
    action: "Review ERU-A7-03 supply airflow setpoint in BAS — adjust to reflect installed airflow if needed.",
    source: "TAB Notes — ERU-A7-03",
    status: "OPEN",
  },
  {
    id: 15,
    priority: "LOW",
    unit: "VAV-A9-18",
    category: "Setpoint Update",
    issue: "Duct to grille #2 deleted. Design CFM reduced from 500 → 250 CFM for that outlet.",
    action: "Update VAV-A9-18 zone setpoints in BAS to reflect reduced design CFM for grille #2.",
    source: "TAB Notes — VAV-A9-18",
    status: "OPEN",
  },
  {
    id: 16,
    priority: "LOW",
    unit: "VAV-A9-20",
    category: "Setpoint Update",
    issue: "One supply grille in area 9-204 deleted. 300 CFM redistributed to 4 remaining grilles.",
    action: "Verify zone setpoint for VAV-A9-20 still matches total design CFM. Update if needed.",
    source: "TAB Notes — VAV-A9-20",
    status: "OPEN",
  },
  {
    id: 17,
    priority: "LOW",
    unit: "AHU-A8-01",
    category: "FYI / No Action",
    issue: "Return grilles sized for 3,200 CFM but unit design return is 2,650 CFM. Grilles will read low.",
    action: "No BAS action needed. Note in as-builts to prevent future misdiagnosis of 'low return' condition.",
    source: "TAB Notes — AHU-A8-01",
    status: "NOTED",
  },
  {
    id: 18,
    priority: "LOW",
    unit: "FCU-A7-06",
    category: "FYI / No Action",
    issue: "Unit running at 80% with filter removed. Two motors installed on unit.",
    action: "Note in BAS asset data if runtime/maintenance tracking is active on this unit.",
    source: "TAB Notes — FCU-A7-06",
    status: "NOTED",
  },
];
